version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      TZ: Asia/Taipei
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backup:/backup
    ports:
      - "3306:3306"

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    volumes:
      - ./config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    ports:
      - "8080:80"



  backup:
    depends_on:
      - mysql
    build: ./backup
    container_name: backup
    environment:
      BACKUP_INTERVAL: 3600 # 設置備份間隔時間，單位為秒
      TZ: Asia/Taipei
    volumes:
      - ./backup:/backup
    entrypoint: /backup/backup.sh

volumes:
  mysql_data:
