version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backup:/backup
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql

  backup:
    build: ./backup
    container_name: backup
    depends_on:
      - mysql
    environment:
      BACKUP_INTERVAL: 1 # 設置備份間隔時間，單位為秒
    volumes:
      - ./backup:/backup
    entrypoint: /backup/backup.sh

volumes:
  mysql_data:
