version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qweasd
    volumes:
      - db_data:/var/lib/mysql
      - ./backup:/backup
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: qweasd
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./config.user.inc.php:/etc/phpmyadmin/config.user.inc.php

volumes:
  db_data:
